/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dunst_attendance_register_AccountActivity */

#ifndef _Included_com_dunst_attendance_register_AccountActivity
#define _Included_com_dunst_attendance_register_AccountActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dunst_attendance_register_AccountActivity
 * Method:    getEmail
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_odia_alphabet_application_DrawApp_getEmail
  (JNIEnv *, jobject);

/*
 * Class:     com_dunst_attendance_register_AccountActivity
 * Method:    getPassword
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_odia_alphabet_application_DrawApp_getPassword
  (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
